name: iOS Simulator Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ios-sim:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm deps
        run: |
          corepack enable || true
          npm ci || npm i
          npm i -D @capacitor/cli@^6
          npm i @capacitor/core@^6 @capacitor/ios@^6

      - name: Ensure minimal web folder
        run: |
          mkdir -p www
          [ -f www/index.html ] || echo "<!doctype html><title>Nabo</title>" > www/index.html

      - name: Force fresh iOS platform
        run: |
          rm -rf ios
          npx --yes @capacitor/cli@latest add ios

      - name: Sync iOS
        run: |
          npx --yes @capacitor/cli@latest sync ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods --no-document
          cd ios/App
          pod repo update
          pod install

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build

      - name: Export .app artifact
        run: |
          APP_PATH=$(find build/Build/Products -type d -name "App.app" | head -n 1)
          mkdir -p out && cp -R "$APP_PATH" out/Nabo.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nabo-iOS-Simulator-App
          path: out/Nabo.app
